SCA WIP

diff --git a/src/ml/automl/auto_pytorch/Dockerfile b/src/ml/automl/auto_pytorch/Dockerfile
--- a/src/ml/automl/auto_pytorch/Dockerfile
+++ b/src/ml/automl/auto_pytorch/Dockerfile
@@ -7,7 +7,7 @@ ENV DEBIAN_FRONTEND=noninteractive
 # Check the version of g++ installed
 RUN g++ -v
 
-# Install the git and Auto-PyTorch dependencies (ffmpeg, libsm6, libxext6)
+# Install git and Auto-PyTorch dependencies (ffmpeg, libsm6, libxext6)
 RUN apt-get install -y swig3.0 git ffmpeg libsm6 libxext6 || (\
 apt-get update --fix-missing && apt-get install -y swig3.0 git ffmpeg libsm6 libxext6)
 
@@ -22,7 +22,7 @@ WORKDIR /src/auto_pytorch/
 # Auto-PyTorch requires(?) the submodules to be initialized for tests
 RUN git submodule update --init --recursive
 
-# Install the required dependencies
+# Install required dependencies
 RUN python3 -m pip install swig
 RUN python3 -m pip install setuptools
 RUN python3 setup.py install
@@ -37,12 +37,12 @@ ARG run_tests
 
 # Install test dependencies
 RUN if [ "$run_tests" = true ]; then \
-    python3 -m pip install -e .[test] Cython==0.29.36 gluonts==0.10.* \
-    numpy==1.20.* torch==1.* coverage pytest pytest-cov; fi
+        python3 -m pip install -e .[test] Cython==0.29.36 gluonts==0.10.* \
+        numpy==1.20.* torch==1.* coverage pytest pytest-cov \
+    ; fi
 
 # Remove the test reports if they exist
 RUN rm -f report.xml coverage.xml
-
 
 ### Run unit tests ###
 # These 4 tests hang and cannot exit:
@@ -56,13 +56,14 @@ RUN rm -f report.xml coverage.xml
 # RUN python3 -W ignore -m pytest ./test/test_ensemble/ --cov-report xml:coverage.xml --cov=. --cov-fail-under=1
 # RUN python3 -W ignore -m pytest ./test/test_evaluation/ --cov-report xml:coverage.xml --cov=. --cov-fail-under=1
 
-# RUN  if [ "$run_tests" = true ]; then python3 -W ignore -m pytest ./test/test_api/ \
-#     -k 'not test_tabular_classification and not test_tabular_regression and not test_tabular_classification_test_evaluator and not test_nonsupported_arguments' \
-#     --cov-report xml:coverage.xml --cov=. --cov-fail-under=1; fi
+RUN  if [ "$run_tests" = true ]; then \
+        (python3 -W ignore -m pytest ./test/ -k 'not test_tabular_classification and not test_tabular_regression and not test_tabular_classification_test_evaluator and not test_nonsupported_arguments' --cov-report xml:coverage.xml --cov=. || ls coverage.xml) && \
+        (cat coverage.xml | grep "hits=" | grep -Eo '[0-9]+' | grep -v '^0$' | wc -l || (echo "FAILED" && exit 1)) \
+    ; fi
 
-RUN ls -la && echo "" && python3 -W ignore -m pytest ./test/test_api/ \
-    -k 'not test_tabular_classification and not test_tabular_regression and not test_tabular_classification_test_evaluator and not test_nonsupported_arguments' \
-    --cov-report xml:coverage.xml --cov=.
+# RUN python3 -W ignore -m pytest ./test/test_api/test_base_api.py
+# RUN python3 -W ignore -m pytest ./test/test_api/test_base_api.py -k 'not test_tabular_classification and not test_tabular_regression and not test_tabular_classification_test_evaluator and not test_nonsupported_arguments'
+# RUN python3 -W ignore -m pytest ./test/test_api/test_api.py -k 'not test_tabular_classification and not test_tabular_regression and not test_tabular_classification_test_evaluator and not test_nonsupported_arguments' --cov-report xml:coverage.xml --cov=. || ls coverage.xml
+# RUN python3 -W ignore -m pytest ./test/ -k 'not test_tabular_classification and not test_tabular_regression and not test_tabular_classification_test_evaluator and not test_nonsupported_arguments' --cov-report xml:coverage.xml --cov=. || ls coverage.xml
 
-# Ensure the coverage.xml file is created and some lines are covered
-RUN cat coverage.xml | grep "hits=" | grep -Eo '[0-9]+' | grep -v '^0$' | wc -l
+RUN python3 -c "import torch;print('GPU STATUS:',torch.cuda.is_available())"
diff --git a/src/ml/automl/auto_sklearn/Dockerfile b/src/ml/automl/auto_sklearn/Dockerfile
--- a/src/ml/automl/auto_sklearn/Dockerfile
+++ b/src/ml/automl/auto_sklearn/Dockerfile
@@ -5,16 +5,16 @@ FROM mfeurer/auto-sklearn:master
 # Set non-interactive mode for apt-get to avoid prompts
 ENV DEBIAN_FRONTEND=noninteractive
 
-# # Install the git and Auto-Sklearn dependencies
-# RUN apt-get install -y git || (apt-get update --fix-missing && apt-get install -y git)
+# Install git and auto-sklearn dependencies
+RUN apt-get install -y git || (apt-get update --fix-missing && apt-get install -y git)
 
-# Clone the Auto-Sklearn repository which contains source code and tests
+# Clone the auto-sklearn repository which contains source code and tests
 RUN git clone https://github.com/automl/auto-sklearn.git /src/auto_sklearn
 
-# Set the working directory to the Auto-Sklearn source code
+# Set the working directory to the auto-sklearn source code
 WORKDIR /src/auto_sklearn/
 
-# AutoGluon requires the submodules to be initialized for tests
+# Initialize any submodules
 RUN git submodule update --init --recursive
 
 # Install the required dependencies
@@ -24,7 +24,6 @@ RUN python3 -m pip install -e .[test,examples]
 # Run tests
 ARG run_tests
 RUN if [ "$run_tests" = true ]; then \
-    python3 -m pytest --cov-report xml:coverage.xml --cov=. --cov-fail-under=1; fi
-
-# Ensure the coverage.xml file is created and some lines are covered
-RUN cat coverage.xml | grep "hits=" | grep -Eo '[0-9]+' | grep -v '^0$' | wc -l
+        (python3 -m pytest --cov-report xml:coverage.xml --cov=. --cov-fail-under=1 || ls coverage.xml) && \
+        (cat coverage.xml | grep "hits=" | grep -Eo '[0-9]+' | grep -v '^0$' | wc -l || (echo "FAILED" && exit 1)) \
+    ; fi
diff --git a/src/ml/automl/autogluon/Dockerfile b/src/ml/automl/autogluon/Dockerfile
--- a/src/ml/automl/autogluon/Dockerfile
+++ b/src/ml/automl/autogluon/Dockerfile
@@ -1,31 +1,37 @@
 # Description: Dockerfile for AutoGluon
-FROM autogluon/autogluon:1.0.0-cuda11.8-framework-ubuntu20.04-py3.10
-# FROM autogluon/autogluon:0.8.2-cuda11.7-framework-ubuntu20.04-py3.9
-# FROM autogluon/autogluon:0.5.2-cuda11.2-jupyter-ubuntu20.04-py3.8
+
+# FROM autogluon/autogluon:1.0.0-cuda11.8-framework-ubuntu20.04-py3.10
+# # FROM autogluon/autogluon:0.8.2-cuda11.7-framework-ubuntu20.04-py3.9
+# # FROM autogluon/autogluon:0.5.2-cuda11.2-jupyter-ubuntu20.04-py3.8
+
+FROM pytorch/pytorch:latest
+# FROM pytorch/pytorch:2.3.1-cuda11.8-cudnn8-devel
 
 # Allow torch to access the GPU
-ENV NVIDIA_VISIBLE_DEVICES all
-ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
+ENV NVIDIA_VISIBLE_DEVICES=all
+ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
+
+RUN echo "\n-> OS: $(uname -r)\n-> CUDA_HOME: {$CUDA_HOME}\n-> conda: $(which conda)"
 
 # Set non-interactive mode for apt-get to avoid prompts
 ENV DEBIAN_FRONTEND=noninteractive
 
-RUN echo "\n-> OS: $(uname -r)\n-> CUDA_HOME: {$CUDA_HOME}\n-> conda: $(which conda)"
-
-RUN apt-get update --fix-missing && apt-get install -y graphviz libgraphviz-dev pkg-config
+# Install git and AutoGluon dependencies
+RUN apt-get update --fix-missing && \
+    apt-get install -y git graphviz libgraphviz-dev pkg-config
 
 # Clone the AutoGluon repository which contains source code and tests
-RUN git clone https://github.com/awslabs/autogluon.git /src/autogluon
+RUN rm -rf /src/autogluon && git clone https://github.com/awslabs/autogluon.git /src/autogluon
 
 # Set the working directory to the AutoGluon source code
 WORKDIR /src/autogluon/
 
-# AutoGluon requires the submodules to be initialized for tests
+# Initialize any submodules
 RUN git submodule update --init --recursive
 
 # Configure the packages to be tested
-RUN echo '[tool.setuptools]' >> pyproject.toml
-RUN echo 'packages = ["autogluon","autogluon.common","autogluon.core","autogluon.eda","autogluon.features","autogluon.multimodal","autogluon.tabular","autogluon.timeseries"]' >> pyproject.toml
+RUN echo '[tool.setuptools]' >> pyproject.toml && \
+    echo 'packages = ["autogluon","autogluon.common","autogluon.core","autogluon.eda","autogluon.features","autogluon.multimodal","autogluon.tabular","autogluon.timeseries"]' >> pyproject.toml
 
 # Attempts to allow torch to access GPU.
 # RUN conda install -c conda-forge mamba
@@ -35,43 +41,56 @@ RUN echo 'packages = ["autogluon","autogluon.common","autogluon.core","autogluon
 # RUN python -c "import torch;print('GPU STATUS:',torch.cuda.is_available())"
 
 # Install the required dependencies
-RUN ./full_install.sh
-# RUN pip freeze | grep torch && python -c "import torch;print('GPU STATUS:',torch.cuda.is_available())"
-RUN python -m pip install -e autogluon[tabular,extra,timeseries]
-# RUN pip freeze | grep torch && python -c "import torch;print('GPU STATUS:',torch.cuda.is_available())"
-RUN python -m pip install -e autogluon[test] coverage pytest pytest-cov
-# RUN pip freeze | grep torch && python -c "import torch;print('GPU STATUS:',torch.cuda.is_available())"
-RUN python -m pip install coverage pytest pytest-cov
-# RUN pip freeze | grep torch && python -c "import torch;print('GPU STATUS:',torch.cuda.is_available())"
+RUN ./full_install.sh && \
+    python -m pip install -e autogluon[tabular,extra,timeseries] && \
+    python -m pip install -e autogluon[test] coverage pytest pytest-cov
 
+# Directory to the AutoGluon CI scripts
 ENV CI_DIR=.github/workflow_scripts
 RUN chmod +x $CI_DIR/*.sh
-RUN $CI_DIR/test_common.sh
-RUN $CI_DIR/test_core.sh
+
+# Remove any existing coverage.xml files
+RUN rm -rf ./**/results.xml ./**/coverage.xml ./**/.coverage
+
+# Run the test scripts
+# Common
+RUN sed -i 's/--junitxml=results.xml/--cov-report xml:coverage.xml --cov=. --cov-fail-under=1/g' $CI_DIR/test_common.sh && \
+    $CI_DIR/test_common.sh && (ls common/.coverage || exit)
+    #  && (cp common/.coverage .coverage.common || exit)
+    # $CI_DIR/test_common.sh && (cp common/.coverage .coverage.common || exit)
+
+# Core
+RUN sed -i 's/--junitxml=results.xml/--cov-report xml:coverage.xml --cov=. --cov-fail-under=1/g' $CI_DIR/test_core.sh && \
+    $CI_DIR/test_core.sh && (ls core/.coverage || exit)
+
+# EDA
 # test_eda.sh fails. It is commented out in their CI.
-RUN $CI_DIR/test_eda.sh || echo "FAILED"
-RUN $CI_DIR/test_features.sh
+# RUN sed -i 's/--junitxml=results.xml/--cov-report xml:coverage.xml --cov=. --cov-fail-under=1/g' $CI_DIR/test_eda.sh && \
+#     $CI_DIR/test_eda.sh && (ls eda/.coverage || exit)
 
-RUN $CI_DIR/test_timeseries.sh
-#  || echo "FAILED"
-# RUN /usr/bin/bash $CI_DIR/test_tabular.sh || echo "FAILED"
-# RUN $CI_DIR/test_multimodal.sh || echo "FAILED"
+# Features
+RUN sed -i 's/--junitxml=results.xml/--cov-report xml:coverage.xml --cov=. --cov-fail-under=1/g' $CI_DIR/test_features.sh && \
+    $CI_DIR/test_features.sh && (ls features/.coverage || exit)
 
-# RUN $CI_DIR/test_timeseries.sh || ls -la && ls timeseries/coverage.xml
-# RUN $CI_DIR/test_tabular.sh    || ls -la && ls tabular/coverage.xml
-# RUN $CI_DIR/test_multimodal.sh || ls -la && ls multimodal/coverage.xml
+# Time series
+RUN sed -i 's/--junitxml=results.xml/--cov-report xml:coverage.xml --cov=. --cov-fail-under=1/g' $CI_DIR/test_timeseries.sh && \
+    $CI_DIR/test_timeseries.sh && (ls timeseries/.coverage || exit)
 
-# # # Run tests if the run_tests is set to "true"
-# # ARG run_tests
-# # RUN if [ "$run_tests" = "true" ]; then \
-# #         echo "Installing test dependencies..." && \
-# #         python -m pip install -e autogluon[test] coverage pytest pytest-cov && \
-# #         echo "Running unit tests..." && \
-# #         python -m pytest --cov-report xml:coverage.xml --cov=. --disable-warnings && \
-# #         ls coverage.xml && \
-# #         echo "Tests complete"; \
-# #     else \
-# #         echo "Skipping tests"; \
-# #     fi
+# Multimodal
+RUN sed -i 's/--junitxml=results.xml/--cov-report xml:coverage.xml --cov=. --cov-fail-under=1/g' $CI_DIR/test_multimodal.sh && \
+    $CI_DIR/test_multimodal.sh && (ls multimodal/.coverage || exit)
 
+# Tabular
+RUN sed -i 's/--junitxml=results.xml/--cov-report xml:coverage.xml --cov=. --cov-fail-under=1/g' $CI_DIR/test_tabular.sh && \
+    $CI_DIR/test_tabular.sh && (ls tabular/.coverage || exit)
+
+# Combine coverage.xml files
+RUN ls && echo "--------" && python -m coverage combine ./*/.coverage
+
+RUN ls && echo "--------" && python -m coverage xml -o coverage.xml && ls
+
+# Print the number of lines with non-zero coverage
+RUN cat coverage.xml | grep "hits=" | grep -Eo '[0-9]+' | grep -v '^0$' | wc -l
+
+# Print the GPU status
 RUN python -c "import torch;print('GPU STATUS:',torch.cuda.is_available())"
diff --git a/src/ml/automl/autokeras/Dockerfile b/src/ml/automl/autokeras/Dockerfile
--- a/src/ml/automl/autokeras/Dockerfile
+++ b/src/ml/automl/autokeras/Dockerfile
@@ -5,10 +5,9 @@ FROM tensorflow/tensorflow:latest-gpu
 
 # Set non-interactive mode for apt-get to avoid prompts
 ENV DEBIAN_FRONTEND=noninteractive
-# Install the git and Auto-Keras dependencies
-RUN apt-get install -y git || (apt-get update --fix-missing && apt-get install -y git)
 
-RUN ls -la
+# Install git and Auto-Keras dependencies
+RUN apt-get install -y git || (apt-get update --fix-missing && apt-get install -y git)
 
 # Clone the Auto-Keras repository which contains source code and tests
 RUN rm -rf /src/autokeras && git clone https://github.com/keras-team/autokeras.git /src/autokeras
@@ -16,20 +15,20 @@ RUN rm -rf /src/autokeras && git clone https://github.com/keras-team/autokeras.g
 # Set the working directory to the Auto-Keras source code
 WORKDIR /src/autokeras/
 
-# Auto-Keras requires(?) the submodules to be initialized for tests
-# RUN git submodule update --init --recursive
-
-RUN python --version; python3 --version
+# Initialize any submodules
+RUN git submodule update --init --recursive
 
 # Install the required dependencies
 RUN python3 -m pip install git+https://github.com/keras-team/keras-tuner.git
 RUN python3 -m pip install --upgrade pip
-RUN ls -la && pwd && python3 -m pip install -e .[tests]
+RUN python3 -m pip install -e .[tests]
 
-RUN python3 -m pytest --cov-report xml:coverage.xml --cov=. --cov-fail-under=1
+RUN if [ "$run_tests" = "true" ]; then \
+        (python3 -m pytest --cov-report xml:coverage.xml --cov=. --cov-fail-under=1 || ls coverage.xml) && \
+        (cat coverage.xml | grep "hits=" | grep -Eo '[0-9]+' | grep -v '^0$' | wc -l || (echo "FAILED" && exit 1)) \
+    ; fi
+
 # RUN python3 -m pytest --cov-report xml:coverage.xml --cov=. --cov-fail-under=1 || ls coverage.xml
-
-# Ensure the coverage.xml file is created and some lines are covered
-RUN cat coverage.xml | grep "hits=" | grep -Eo '[0-9]+' | grep -v '^0$' | wc -l
+# RUN ls && (cat coverage.xml | grep "hits=" | grep -Eo '[0-9]+' | grep -v '^0$' | wc -l || (echo "FAILED" && exit 1))
 
 RUN python -c "import tensorflow as tf;print('GPU STATUS:',tf.test.is_built_with_cuda())"
diff --git a/src/ml/automl/autots/Dockerfile b/src/ml/automl/autots/Dockerfile
--- a/src/ml/automl/autots/Dockerfile
+++ b/src/ml/automl/autots/Dockerfile
@@ -6,7 +6,7 @@ FROM tensorflow/tensorflow:latest-gpu
 ENV DEBIAN_FRONTEND=noninteractive
 
 # Install the git and AutoTS dependencies
-RUN apt-get update --fix-missing && apt-get install -y git
+RUN apt-get update --fix-missing && apt-get install -y git build-essential
 
 # Clone the AutoTS repository which contains source code and tests
 RUN rm -rf /src/autots && git clone https://github.com/winedarksea/AutoTS.git /src/autots
@@ -16,20 +16,14 @@ WORKDIR /src/autots/
 
 # Install the required dependencies
 RUN python3 -m pip install --upgrade pip
-RUN python3 -m pip install -e .['additional']
+RUN python3 -m pip install -e .['additional'] pytest-cov
 
 # Run unit tests if the run_tests is set to "true"
 ARG run_tests
-RUN if [ "$run_tests" = "true" ]; then \
-        echo "Installing test dependencies..." && \
-        python3 -m pip install -e .['additional'] coverage pytest pytest-cov && \
-        echo "Running unit tests..." && \
-        python3 -m pytest ./tests/ --cov-report xml:coverage.xml --cov=. && \
-        ls coverage.xml && \
-        echo "Tests complete"; \
-    else \
-        echo "Skipping tests"; \
-    fi
-    # || ls coverage.xml
+RUN if [ "$run_tests" = true ]; then \
+        (python3 -W ignore -m pytest ./tests/ --cov-report xml:coverage.xml --cov=. --cov-fail-under=1 || ls coverage.xml) && \
+        (cat coverage.xml | grep "hits=" | grep -Eo '[0-9]+' | grep -v '^0$' | wc -l || (echo "FAILED" && exit 1)) \
+    ; fi
+
 # Check GPU access
 RUN python -c "import tensorflow as tf;print('GPU STATUS:',tf.test.is_built_with_cuda())"
diff --git a/src/ml/automl/evalml/Dockerfile b/src/ml/automl/evalml/Dockerfile
--- a/src/ml/automl/evalml/Dockerfile
+++ b/src/ml/automl/evalml/Dockerfile
@@ -14,15 +14,19 @@ RUN rm -rf /src/evalml && git clone https://github.com/alteryx/evalml.git /src/e
 # Set the working directory to the EvalML source code
 WORKDIR /src/evalml/
 
-# Set the test timeout
-ENV TIMEOUT=3600
+# Install the required dependencies
+ARG run_tests
+RUN if [ "$run_tests" = "true" ]; then make installdeps-dev; fi
+RUN if [ "$run_tests" = "true" ]; then make installdeps-prophet; fi
+RUN if [ "$run_tests" = "true" ]; then make installdeps-test; fi
 
-# ARG run_tests
-# RUN if [ "$run_tests" = "true" ]; then make installdeps-dev; fi
-# RUN if [ "$run_tests" = "true" ]; then make installdeps-prophet; fi
-# RUN if [ "$run_tests" = "true" ]; then make installdeps-test; fi
-
-# # RUN if [ "$run_tests" = "true" ]; then pip freeze && (TIMEOUT=$TIMEOUT make test); fi
+# Run tests
+# RUN if [ "$run_tests" = "true" ]; then pip freeze && (TIMEOUT=$TIMEOUT make test); fi
 # RUN if [ "$run_tests" = "true" ]; then pip freeze && make test; fi
+RUN if [ "$run_tests" = "true" ]; then \
+        pip freeze && \
+        (pytest evalml/ --doctest-modules --doctest-continue-on-failure  --timeout 3600 --cov-report xml:coverage.xml --cov=. --cov-fail-under=1 || ls coverage.xml) && \
+        (cat coverage.xml | grep "hits=" | grep -Eo '[0-9]+' | grep -v '^0$' | wc -l || (echo "FAILED" && exit 1)) \
+    ; fi
 
-# RUN python -c "import torch;print('GPU STATUS:',torch.cuda.is_available())"
+RUN python -c "import tensorflow as tf;print('GPU STATUS:',tf.config.list_physical_devices('GPU'))"
