Update .gitignore to exclude .gv and .profile files; enhance Dockerfile test coverage command with failure handling

diff --git a/src/ml/automl/pycaret/Dockerfile b/src/ml/automl/pycaret/Dockerfile
--- a/src/ml/automl/pycaret/Dockerfile
+++ b/src/ml/automl/pycaret/Dockerfile
@@ -77,8 +77,8 @@ ARG run_tests
 RUN if [ "$run_tests" = "true" ]; then \
         rm -rf coverage.xml && \
         echo "Running unit tests..." && \
-        (python3 -m pytest --cov-branch --cov-report xml:coverage.xml --cov=. || ls coverage.xml)&& \
-        cat coverage.xml | grep "hits=" | grep -Eo '[0-9]+' | grep -v '^0$' | wc -l && \
+        (python3 -m pytest --cov-branch --cov-report xml:coverage.xml --cov=. --cov-fail-under=1 || ls coverage.xml) && \
+        (cat coverage.xml | grep "hits=" | grep -Eo '[0-9]+' | grep -v '^0$' | wc -l || (echo "FAILED" && exit 1)) && \
         echo "Tests complete"; \
     else \
         echo "Skipping tests"; \
